# [START app_yaml]
runtime: nodejs18

# service: my-next-app

env_variables:
  NODE_ENV: 'production'
  BACKEND_URL: ${BACKEND_URL}

handlers:
  - url: /_next/static
    static_dir: .next/static
    secure: always

  - url: /images/.*
    static_dir: public/images
    secure: always
    http_headers:
      Cache-Control: "no-store"

  - url: /.*
    secure: always
    script: auto

# [END app_yaml]